<?php

namespace App\Enums;

enum UserInterest: string
{
    case Gaming = 'gaming';
    case Music = 'music';
    case Tech = 'tech';
    case Art = 'art';
    case Travel = 'travel';
    case Movies = 'movies';
    case Sport = 'sport';
    case Science = 'science';
    case Fashion = 'fashion';
    case Coding = 'coding';
    case Crypto = 'crypto';
    case Anime = 'anime';
    case Fitness = 'fitness';
    case Cooking = 'cooking';
    case Business = 'business';
    case Photography = 'photography';
    case Books = 'books';
    case Writing = 'writing';
    case Design = 'design';
    case Marketing = 'marketing';
    case Startups = 'startups';
    case AI = 'ai';
    case Psychology = 'psychology';
    case Philosophy = 'philosophy';
    case History = 'history';
    case Languages = 'languages';
    case Cars = 'cars';
    case Architecture = 'architecture';
    case Astronomy = 'astronomy';
    case Ecology = 'ecology';
    case Finance = 'finance';
    case Investing = 'investing';
    case RealEstate = 'real_estate';
    case Yoga = 'yoga';
    case Meditation = 'meditation';
    case Volunteering = 'volunteering';
    case DIY = 'diy';
    case Crafts = 'crafts';
    case GamingDev = 'game_dev';
    case Cybersecurity = 'cybersecurity';
    case DataScience = 'data_science';
    case CryptoTrading = 'crypto_trading';
    case Podcasting = 'podcasting';
    case Blogging = 'blogging';
    case Theater = 'theater';
    case Dance = 'dance';
    case BoardGames = 'board_games';
    case Esport = 'esport';
    case UFC = 'ufc';
    case Football = 'football';
    case Basketball = 'basketball';
    case Formula1 = 'formula1';
    case Hiking = 'hiking';
    case Camping = 'camping';
    case Pets = 'pets';
    case Gardening = 'gardening';
    case Wine = 'wine';
    case Coffee = 'coffee';
    case Health = 'health';
    case Biohacking = 'biohacking';
    case Spirituality = 'spirituality';
    case Astrology = 'astrology';
    case VR = 'vr';
    case Robotics = 'robotics';
}